
default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: twitterclone2_development


test:
  <<: *default
  database: twitterclone2_test

production:
  <<: *default
  database: twitterclone2_production
  username: twitterclone2
  password: <%= ENV['TWITTERCLONE2_DATABASE_PASSWORD'] %>
